# Generated by Django 5.1.1 on 2024-09-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
