# Generated by Django 5.1.1 on 2024-09-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pop', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
